### ISSUE TITLE
Fix FileNotFoundError because of hardcoded filepath for ShellPymyapp.log

### ISSUE THREAD

**Issue by raajtilaksarma** [jptalukdar/ShellPy#6]
```
>>> from ShellPy.Engine.Commands import commandsManager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/wsl-shared/ShellPy/ShellPy/Engine/Commands/commandsManager.py", line 10, in <module>
    filemode='w+')
  File "/usr/lib/python3.6/logging/__init__.py", line 1808, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode,    @@@encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: `'/mnt/c/wsl-shared/ShellPy/D:/Github/ShellPy/LOGS/ShellPymyapp.log'`
```

**Comment by jptalukdar** [comment]
Fixed and merged to Master Branch
